# Generated by Django 4.2 on 2025-10-09 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('afiliados', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPractica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la categoría de práctica', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría de Práctica',
                'verbose_name_plural': 'Categorías de Prácticas',
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('nro_de_orden', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de emisión de la orden')),
                ('fecha_prestacion', models.DateTimeField(blank=True, help_text='Fecha en que se realizará o realizó la prestación', null=True)),
                ('prestador', models.CharField(help_text='Nombre del prestador o institución que brindará el servicio', max_length=255)),
                ('diagnostico', models.CharField(blank=True, help_text='Diagnóstico o motivo de la consulta', max_length=255)),
                ('activo', models.BooleanField(default=True, help_text='Indica si la orden de prestación está activa o fue dada de baja')),
                ('tipo', models.CharField(choices=[('consulta', 'Consulta médica'), ('practica', 'Bono de prácticas')], default='consulta', help_text='Tipo de orden: Consulta médica o Bono de prácticas', max_length=10)),
                ('codigo_seguridad', models.CharField(blank=True, editable=False, help_text='Código de seguridad único para la orden de prestación', max_length=255)),
                ('afiliado', models.ForeignKey(help_text='Afiliado al que se le emite la orden de prestación', on_delete=django.db.models.deletion.PROTECT, related_name='consultas_afiliado', to='afiliados.afiliado', to_field='nrodoc')),
                ('obra_social', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to='afiliados.obrasocial')),
                ('usuario', models.ForeignKey(help_text='Usuario que emite la orden', on_delete=django.db.models.deletion.PROTECT, related_name='consultas_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='Practica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codPractica', models.CharField(help_text='Código de la práctica asociada', max_length=9, unique=True, verbose_name='Código de Práctica')),
                ('descripcion', models.CharField(help_text='Descripción de la práctica asociada', max_length=255)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Precio de la práctica', max_digits=10, null=True)),
                ('categoria', models.ForeignKey(blank=True, help_text='Categoría a la que pertenece la práctica', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='practicas', to='consultas.categoriapractica')),
            ],
            options={
                'verbose_name': 'Codigo de Práctica',
                'verbose_name_plural': 'Prácticas',
            },
        ),
        migrations.CreateModel(
            name='PracticaConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStamp', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro')),
                ('consulta', models.ForeignKey(help_text='Pactica as asociadas a la consulta', on_delete=django.db.models.deletion.CASCADE, related_name='practicas_consulta', to='consultas.consulta')),
                ('practica', models.ForeignKey(help_text='Práctica asociada a la consulta', on_delete=django.db.models.deletion.CASCADE, related_name='practicas', to='consultas.practica')),
            ],
            options={
                'verbose_name': 'Práctica en Bono',
                'verbose_name_plural': 'Prácticas en Bono',
                'unique_together': {('consulta', 'practica')},
            },
        ),
    ]
