# Generated by Django 4.2 on 2025-05-30 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('afiliados', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('nro_de_orden', models.AutoField(primary_key=True, serialize=False)),
                ('prestador', models.CharField(max_length=255)),
                ('fecha_emision', models.DateTimeField()),
                ('fecha_prestacion', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True, help_text='Indica si la orden de prestación está activa o fue dada de baja')),
                ('afiliado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas_afiliado', to='afiliados.afiliado', to_field='cuil')),
                ('obra_social', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to='afiliados.obrasocial')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['-fecha_emision'],
            },
        ),
    ]
