# Generated by Django 4.2 on 2025-12-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicaconsulta',
            name='cantidad',
            field=models.PositiveIntegerField(default=2, help_text='Cantidad de veces que se realiza la práctica'),
        ),
    ]
