# Generated by Django 4.2 on 2026-03-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_practicaconsulta_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicaconsulta',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, help_text='Cantidad de veces que se realiza la práctica'),
        ),
    ]
