# Generated by Django 4.2 on 2025-06-10 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0004_alter_afiliado_cuil_alter_afiliado_nrodoc'),
        ('consultas', '0002_consulta_diagnostico_alter_consulta_fecha_emision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='afiliado',
            field=models.ForeignKey(help_text='Afiliado al que se le emite la orden de prestación', on_delete=django.db.models.deletion.PROTECT, related_name='consultas_afiliado', to='afiliados.afiliado', to_field='nrodoc'),
        ),
    ]
