# Generated by Django 4.2 on 2025-06-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0003_alter_consulta_afiliado'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='codigo_seguridad',
            field=models.CharField(blank=True, editable=False, help_text='Código de seguridad único para la orden de prestación', max_length=255),
        ),
    ]
