# Generated by Django 4.2 on 2025-06-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0004_consulta_codigo_seguridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='tipo',
            field=models.CharField(choices=[('consulta', 'Consulta médica'), ('practica', 'Bono de prácticas')], default='consulta', help_text='Tipo de orden: Consulta médica o Bono de prácticas', max_length=10),
        ),
    ]
