# Generated by Django 4.2 on 2025-05-30 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObraSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_id', models.CharField(max_length=255, unique=True)),
                ('os_nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Obra Social',
                'verbose_name_plural': 'Obras Sociales',
            },
        ),
        migrations.CreateModel(
            name='Afiliado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ben_id', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('tipodoc_co', models.CharField(max_length=255)),
                ('nrodoc', models.CharField(max_length=255)),
                ('cuil', models.CharField(max_length=255, unique=True)),
                ('sexo', models.CharField(max_length=255)),
                ('edad', models.CharField(max_length=255)),
                ('nomplan', models.CharField(max_length=255)),
                ('grupofliar', models.CharField(max_length=255)),
                ('parentesco', models.CharField(max_length=255)),
                ('loc_id', models.CharField(max_length=255)),
                ('localidad', models.CharField(max_length=255)),
                ('codpostal', models.CharField(max_length=255)),
                ('prov_nombr', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=255)),
                ('calle', models.CharField(max_length=255)),
                ('fecha_alta', models.CharField(max_length=255)),
                ('fecha_baja', models.CharField(max_length=255)),
                ('sucursal', models.CharField(max_length=255)),
                ('cobrador', models.CharField(max_length=255)),
                ('coberturae', models.CharField(max_length=255)),
                ('patologias', models.CharField(max_length=255)),
                ('deuda_fact', models.CharField(max_length=255)),
                ('subconveni', models.CharField(max_length=255)),
                ('condiva_af', models.CharField(max_length=255)),
                ('incapacida', models.CharField(max_length=255)),
                ('plan_id', models.CharField(max_length=255)),
                ('ben_email', models.CharField(max_length=255)),
                ('grupo_etar', models.CharField(max_length=255)),
                ('tipoben_no', models.CharField(max_length=255)),
                ('depben_nom', models.CharField(max_length=255)),
                ('estado_afi', models.CharField(max_length=255)),
                ('observa', models.CharField(max_length=255)),
                ('cuotas_deu', models.CharField(max_length=255)),
                ('fechanac', models.CharField(max_length=255)),
                ('incluido', models.CharField(max_length=255)),
                ('obra_social', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='afiliados', to='afiliados.obrasocial')),
            ],
            options={
                'verbose_name': 'Afiliado',
                'verbose_name_plural': 'Afiliados',
            },
        ),
    ]
