# Generated by Django 4.2 on 2025-06-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='afiliado',
            name='baja',
            field=models.BooleanField(default=False),
        ),
    ]
