# Generated by Django 4.2 on 2026-03-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='obrasocial',
            name='activa',
            field=models.BooleanField(default=True),
        ),
    ]
