# Generated by Django 4.2 on 2025-06-10 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0002_afiliado_baja'),
    ]

    operations = [
        migrations.AddField(
            model_name='afiliado',
            name='fecha_importacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='AfiliadoHistorialObraSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('afiliado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afiliados.afiliado')),
                ('obra_social', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='afiliados.obrasocial')),
            ],
        ),
    ]
