# Generated by Django 4.2 on 2026-03-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0002_obrasocial_activa'),
    ]

    operations = [
        migrations.AddField(
            model_name='obrasocial',
            name='fecha_alta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obrasocial',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True),
        ),
    ]
