# Generated by Django 4.2 on 2026-03-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0003_obrasocial_fecha_alta_obrasocial_fecha_baja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afiliado',
            name='fecha_alta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='fecha_baja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
