# Generated by Django 4.2 on 2025-06-10 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0003_afiliado_fecha_importacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afiliado',
            name='cuil',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='nrodoc',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
