# Generated by Django 4.2 on 2025-06-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0004_alter_afiliado_cuil_alter_afiliado_nrodoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afiliado',
            name='cuil',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
