# Generated by Django 4.2 on 2025-08-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0005_alter_afiliado_cuil'),
    ]

    operations = [
        migrations.AddField(
            model_name='obrasocial',
            name='coseguro',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='obrasocial',
            name='monto_coseguro',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
